# Generated by Django 5.2.4 on 2025-08-07 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="test@example.com", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Test", max_length=50),
        ),
    ]
